CREATE TABLE items (
  id int generated by default as identity,
  publish_date date,
  archived boolean,
  genre_id int,
  author_id int,
  label_id int,
  PRIMARY KEY (id)
)

CREATE TABLE authors (
  id int generated by default as identity,
  first_name varchar,
  last_name varchar,
  PRIMARY KEY (id)
);

CREATE TABLE games (
  item_id int,
  multiplayer boolean,
  last_played_at date,
  PRIMARY KEY (item_id)
);

CREATE TABLE label (
  id SERIAL PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  color VARCHAR(100) NOT NULL
);

CREATE TABLE books (
  id INT PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  cover_state VARCHAR(255),
  publish_date DATE NOT NULL,
  archived BOOLEAN NOT NULL,
  FOREIGN KEY(id) REFERENCES items(id)
);

CREATE TABLE music_albums (
  id INT PRIMARY KEY,
  on_spotify BOOLEAN NOT NULL,
  publish_date DATE NOT NULL,
  archived BOOLEAN NOT NULL,
  genre_id INT REFERENCES genres(id),
  label_id INT REFERENCES labels(id), 
);

CREATE TABLE genres (
  id INT PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);
